### ISSUE TITLE
Acceptance of WWW

### ISSUE THREAD

**Issue by XingyuLu206** [HestiaSky/LLaMA_SRank#2]
Dear authors of E4SRec:
 I have seen your paper from https://arxiv.org/pdf/2312.02443.pdf, and it specified that your work has been accepted by WWW'24. I am also an author and wonder if the acceptance result of WWW has been settled, could you please share some information about WWW'24 with me? Which is of vital importance for my work arrangement.

**Comment by HestiaSky** [comment]
Hi, thanks for your interest.
We didn't specify that this work has been accepted by WWW and we merely used the template for convenience.
