### ISSUE TITLE
Hyperparameters on Yelp

### ISSUE THREAD

**Issue by woriazzc** [HestiaSky/LLaMA_SRank#6]
Hi! I am trying to reproduce the results on Yelp.
May I ask what are your hyperparameter settings on Yelp?

**Comment by HestiaSky** [comment]
For the hyperparameters, please kindly refer to Table 5 in appendix.
Also, it is mandatory to further tune the hyperparameters since LLMs are very sensitive to hyperparameters and the different environments may result in different training process.
